name: MySystemInfo
version: '${project.version}'
main: io.github.bravecake.mysysteminfo.Main
api-version: '1.20'
authors: [BraveCake]
description: a utility plugin for showing host info
permissions:
  systeminfo.view:
    description: Allows players to view system information
    default: op
commands:
  systeminfo:
    description: Shows info about the server hosting device
    permission: systeminfo.view
    aliases: [SystemInfo, sysinfo,systemInfo]